language: java
jdk:
  - oraclejdk8
install: mvn clean compile sonar:sonar -Dsonar.organization=sebastien49170-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b4e506f092c780a785eea116b14bde33727a23ab
